### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [mulander/oracle.tmbundle#14]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by mulander** [comment]
Hi @arfon,

I licensed the repository as GNU GPL v2 because the code was derived from a GPL v2 versioned tmbundle as correctly mentioned in the [previous issue you filed](https://github.com/mulander/oracle.tmbundle/issues/11#issuecomment-73514479).

I am not a lawyer and don't want to be responsible for re-licensing the code in an incompatible way. If you want to take that risk personally you can fork and re-license the codebase assuming that all my code additions can be treated as dual licensed on ISC and GPL v2.

Regards,
Adam

**Comment by arfon** [comment]
> I licensed the repository as GNU GPL v2 because the code was derived from a GPL v2 versioned tmbundle as correctly mentioned in the previous issue you filed.

Hi @mulander - my apologies - I completely missed that I'd asked this of you before. I agree with your assessment.

Thanks for the quick response :-)
